<a href="https://colab.research.google.com/github/shadbucet/app-pshell/blob/master/numpy_1_udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 2.x


TensorFlow 2.x selected.


import tensorflow as tf

In [4]:
tf.__version__

'2.1.0'

In [5]:
print("Shadab")

Shadab


In [0]:
import numpy as np

mylist_n = [[1,2],[3,4],[5,6]]

In [11]:
np.array(mylist_n)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.ones((3,3), dtype=None)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace()

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.randn()

array([[ 1.56011785, -0.37955113, -0.68678026],
       [ 0.20872209, -0.22949523, -0.78163829],
       [-1.95215652,  0.69844846, -0.39728363]])

In [31]:
np.random.randint(1,100,(2,3))

array([[66, 74, 51],
       [34, 97, 78]])

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.random.randint(1,100,10)
arr

array([88, 30, 38,  2, 64, 60, 21, 33, 76, 58])

In [36]:
arr.argmax()

0